---
label: Project
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: text
  name: subtitle
  label: subtitle
- type: file
  name: photo
  label: photo
- type: textarea
  name: summary
  label: summary
pages:
- content/projects/collections-dive.md
- content/projects/feed-finder.md
- content/projects/irismsg-io.md
- content/projects/sleepful.me.md
- content/projects/thinkactive-io.md
